#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=34 blur_radius=30 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Semibold:11.0"
  # label.font="SF Pro:Heavy:11.0"

  label.font="MartianMono Nerd Font:Bold:10.0"

  #Item Background
  background.color=$ITEM_BG_COLOR
  background.corner_radius=4
  background.height=24

  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=5
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=5
)
sketchybar --default "${default[@]}"

# Right Side Items
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
# source $ITEM_DIR/wifi.sh

source $ITEM_DIR/media.sh

# #Apple Popup Logo
# #!/usr/bin/env bash

# sketchybar -m --bar blur_radius=50                                                            \
#                     height=32                                                                 \
#               --add item apple.logo left                                                      \
#               --set apple.logo icon=􀣺                                                         \
#                                icon.font="SF Pro:Black:16.0"                                  \
#                                label.drawing=off                                              \
#                                icon.padding_left=7 \
#                                icon.padding_right=7 \
#                                click_script="sketchybar -m --set \$NAME popup.drawing=toggle" \
#                                popup.background.border_width=2                                \
#                                popup.background.corner_radius=3                                \
#                                popup.background.border_color=0xff9dd274                       \
#                                                                                               \
#               --default background.padding_left=5                                             \
#                         background.padding_right=5                                            \
#                         icon.padding_right=5                                                  \
#                         icon.font="SF Pro:Bold:16.0"                                          \
#                         label.font="SF Pro:Semibold:13.0"                                     \
#                                                                                               \
#               --add item apple.preferences popup.apple.logo                                   \
#               --set apple.preferences icon=􀺻                                                  \
#                                label="Settings"                                            \
#                                click_script="open -a 'System Preferences';
#                                              sketchybar -m --set apple.logo popup.drawing=off"\
#               --add item apple.activity popup.apple.logo                                      \
#               --set apple.activity icon=􀒓                                                     \
#                                label="Activity"                                               \
#                                click_script="open -a 'Activity Monitor';
#                                              sketchybar -m --set apple.logo popup.drawing=off"\
#               --add item apple.lock popup.apple.logo                                          \
#               --set apple.lock icon=􀒳                                                         \
#                                label="Lock Screen"                                            \
#                                click_script="pmset displaysleepnow;
#                                              sketchybar -m --set apple.logo popup.drawing=off"


#Left Side Items
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
